# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jgiron <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/07/29 16:15:20 by jgiron            #+#    #+#              #
#    Updated: 2021/01/30 19:48:01 by jgiron           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM	alpine:3.12

RUN	apk update && apk add mariadb mariadb-client openrc && apk add --no-cache --upgrade bash

RUN	mkdir /run/mysqld/
RUN	openrc boot

COPY	srcs/init/init.sh	/tmp/
COPY	srcs/mysql.conf		/tmp/
COPY	srcs/my.cnf		/etc/my.cnf
COPY	srcs/wordpress_dump.sql	/tmp/wordpress_dump.sql

CMD	["/tmp/init.sh"]
