# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    grafana.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jgiron <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/10/15 16:00:14 by jgiron            #+#    #+#              #
#    Updated: 2020/10/22 16:14:37 by jgiron           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: ft_grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: telegraf-endpoint
          mountPath: "/var/run/docker.sock"
        livenessProbe:
#          httpGet:
#            path: /login
#            port: 3000
#            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep -v grep | grep "telegraf" && ps aux | grep -v grep | grep "grafana-server"
      volumes:
      - name: telegraf-endpoint
        hostPath:
          path: /var/run/docker.sock

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: cluster
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - name: grafana-https
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf-account
  labels:
    app: influxdb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: telegraf-account
  namespace: default
