# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    phpmyadmin.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jgiron <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/10/15 16:00:14 by jgiron            #+#    #+#              #
#    Updated: 2020/10/22 16:14:37 by jgiron           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: ft_phpmyadmin:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: cluster
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
    - name: phpmyadmin-https
      protocol: TCP
      port: 5000
      targetPort: 443
  type: LoadBalancer
