# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    wordpress.yaml                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jgiron <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/10/15 16:00:14 by jgiron            #+#    #+#              #
#    Updated: 2020/10/22 16:14:37 by jgiron           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: ft_wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: cluster
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - name: wordpress-https
      protocol: TCP
      port: 5050
      targetPort: 443
  type: LoadBalancer
