# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    wordpress.yaml                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jgiron <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/10/15 16:00:14 by jgiron            #+#    #+#              #
#    Updated: 2020/10/22 16:14:37 by jgiron           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: ft_wordpress:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 443
        livenessProbe:
#          httpGet:
#            path: /index.php
#            port: 443
#            scheme: HTTPS
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep -v grep | grep "php-fpm" && ps aux | grep -v grep | grep "nginx"
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: cluster
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - name: wordpress-https
      protocol: TCP
      port: 5050
      targetPort: 443
  type: LoadBalancer
