# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jgiron <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/07/29 16:15:20 by jgiron            #+#    #+#              #
#    Updated: 2021/01/30 19:39:22 by jgiron           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM	alpine:3.12

RUN		apk update && apk add bash git vim nginx openssl openrc php7 php7-fpm php7-opcache curl php7-gd php7-mysqli php7-zlib php7-curl

RUN		apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main libc6-compat

RUN		mkdir /run/nginx /run/php-fpm7/ && rm /etc/nginx/conf.d/*
RUN		adduser -g www -h /home/www/ -D  www

RUN		mkdir /etc/nginx/ssl/ && \
		openssl req -x509 -nodes -days 365 -newkey rsa:4096 \
		-subj '/C=FR/ST=75/L=Paris/O=42/CN=jgiron' \
		-keyout /etc/nginx/ssl/localhost.key -out /etc/nginx/ssl/localhost.crt;
RUN		ssh-keygen -A

COPY	srcs/init/init.sh		/tmp/
COPY	srcs/nginx/localhost.conf	/etc/nginx/conf.d/

COPY	srcs/html/ /var/www/localhost

EXPOSE  80 443 

CMD		["/tmp/init.sh"]
