# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jgiron <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/07/29 16:15:20 by jgiron            #+#    #+#              #
#    Updated: 2020/08/17 18:07:56 by jgiron           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM	alpine

RUN		apk update && apk add zsh bash git vim openssl vsftpd

COPY	srcs/init/init.sh /tmp/

EXPOSE  21 443 22

CMD		["/tmp/init.sh"]
