# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jgiron <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/07/29 16:15:20 by jgiron            #+#    #+#              #
#    Updated: 2021/01/30 19:42:39 by jgiron           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM	alpine:3.12

RUN	apk update && apk add bash git openssl vsftpd openrc
RUN	mkdir /srv/ftp
RUN	chown nobody:nogroup /srv/ftp
RUN	echo "anon" | tee /srv/ftp/anon.txt
RUN	echo root:root | chpasswd
RUN	mkdir -p /etc/ssl-vsftpd/private && \
	openssl req -x509 -nodes -days 365 -newkey rsa:4096 \
	-subj '/C=FR/ST=75/L=Paris/O=42/CN=jgiron' \
	-keyout /etc/ssl-vsftpd/private/localhost.key -out /etc/ssl-vsftpd/private/localhost.crt;
RUN	openrc boot

COPY	srcs/init/init.sh	/tmp/
COPY	srcs/vsftpd/vsftpd.conf	/etc/vsftpd/vsftpd.conf
COPY	srcs/telegraf.conf	/etc/telegraf/


EXPOSE  21 64000

CMD	["/tmp/init.sh"]
